#!/usr/bin/env bash

sb_mboxtrain.py -d "$MAILDIR"/spambayes.db -s /home/kyrias/.cache/learn-spam -r
rsync "$MAILDIR"/spambayes.db \
      kyrias@theos.kyriasis.com:Mail/spambayes.db \
      --update --checksum --human-readable --progress
