#!/usr/bin/env bash

create_snapshot() {
	local from="$1"
	local to="$2"/"$(date +%Y-%m-%dT%H:%M:%S%z)"
	sudo mkdir "$to"
	sudo btrfs subvolume snapshot -r "$from" "$to" &&
	    printf "==> Successfully created a snaphot of %s in %s\n" "$from" "$to" ||
	    printf "==> Failet to create a snaphot of %s in %s\n"     "$from" "$to"
}


main() {
	local rootmount=/media/"$SHORTHOST"-ssd-1
	printf "==> Creating snapshots in %s\n" "$rootmount"

	create_snapshot "$rootmount"/root "$rootmount"/snap-root
	create_snapshot "$rootmount"/home "$rootmount"/snap-home
}


main "$@"
