#!/usr/bin/env bash

if [[ -n "$2" ]]; then
	step=$2
else
	step=5
fi

case $1 in
	lower)
		pactl set-sink-mute 1 false
		pactl set-sink-volume 1 -"$step"%
		;;
	raise)
		pactl set-sink-mute 1 false
		pactl set-sink-volume 1 +"$step"%
		;;
	mute)
		pactl set-sink-mute 1 toggle
		;;
	mute-mic)
		pactl set-source-mute 2 toggle
		;;
esac
