#!/usr/bin/env zsh

step=5
sink="@DEFAULT_SINK@"
source="@DEFAULT_SOURCE@"

if [[ "$#" -eq 3 ]]; then
	step="$2"
	sink="$3"
elif [[ "$#" -eq 2 ]]; then
	step="$2"
fi

case $1 in
	lower)
		pactl set-sink-volume "$sink" -"$step"%
		;;
	raise)
		pactl set-sink-volume "$sink" +"$step"%
		;;
	mute)
		pactl set-sink-mute "$sink" toggle
		;;
	mute-mic)
		pactl set-source-mute "$source" toggle
		;;
esac
